
export enum GradoInstruccionEnum {
  EDUCACION_INICIAL_COMPLETA = 'EDUCACION_INICIAL_COMPLETA',
  EDUCACION_INICIAL_INCOMPLETA = 'EDUCACION_INICIAL_INCOMPLETA',
  PRIMARIA_COMPLETA = 'PRIMARIA_COMPLETA',
  PRIMARIA_INCOMPLETA = 'PRIMARIA_INCOMPLETA',
  SECUNDARIA_COMPLETA = 'SECUNDARIA_COMPLETA',
  SECUNDARIA_INCOMPLETA = 'SECUNDARIA_INCOMPLETA',
  EDUCACION_SUPERIOR_TECNICA_COMPLETA = 'EDUCACION_SUPERIOR_TECNICA_COMPLETA',
  EDUCACION_SUPERIOR_TECNICA_INCOMPLETA = 'EDUCACION_SUPERIOR_TECNICA_INCOMPLETA',
  EDUCACION_SUPERIOR_UNIVERSITARIA_COMPLETA = 'EDUCACION_SUPERIOR_UNIVERSITARIA_COMPLETA',
  EDUCACION_SUPERIOR_UNIVERSITARIA_INCOMPLETA = 'EDUCACION_SUPERIOR_UNIVERSITARIA_INCOMPLETA',
  SIN_INSTRUCCION = 'SIN_INSTRUCCION'
}